baseURL = 'https://example.org/'
languageCode = 'es'
title = 'Van Klimen'
subtitle = 'Manual Algorítmico para Artistas'


[permalinks]
  blog = "/:contentbasename/"
  acerca = "/:contentbasename/"

sectionPagesMenu = 'main'

[taxonomies]
  autor = "autores"

[params]
  dateFormat = "02/01"
  homeText = "Manual Algorítmico para Artistas"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    
[markup.goldmark.parser.attribute]
  block = true
  title = true