baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Van Klimen'


[permalinks]
  blog = "/:contentbasename/"
  acerca = "/:contentbasename/"

[menu]
  [[menu.main]]
    name = "Inicio"
    # Change 'url' to 'pageRef'
    pageRef = "/" 
    weight = 1
    identifier = "home"


sectionPagesMenu = 'main'

[taxonomies]
  tag = "tags"

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Manual Algor√≠tmico para Artistas"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true