baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Van Klimen'


[permalinks]
  blog = "/:contentbasename/"
  acerca = "/:contentbasename/"

sectionPagesMenu = 'main'

[taxonomies]
  tag = "tags"

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Manual Algor√≠tmico para Artistas"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true